name: Borsa Verilerini Güncelle

on:
  schedule:
    - cron: '0 15 * * 1-5'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: # Buraya da yetki ekleyerek işimizi garantiye alalım
      contents: write
    steps:
      - name: Kodları çek
        uses: actions/checkout@v4 # v3 yerine v4 yaptık

      - name: Python Kur
        uses: actions/setup-python@v5 # v4 yerine v5 yaptık
        with:
          python-version: '3.11'

      - name: Kütüphaneleri Yükle
        run: pip install yfinance

      - name: Botu Çalıştır
        run: python bot.py

      - name: Değişiklikleri Kaydet ve Pushla
        run: |
          git config --global user.name 'GitHub Action Bot'
          git config --global user.email 'action@github.com'
          git add src/App.jsx
          git commit -m "Otomatik borsa fiyat güncellemesi" || echo "Değişiklik yok"
          git push